### ISSUE TITLE
Community Plugin description copy proposals

### ISSUE THREAD

**Issue by ThisIsKeb** [trey-wallis/obsidian-dataloom#617]
### Problem

Hi! Just found your plugin and it is EXACTLY what I am looking for. I really wanted an excel type table view that wasn't as frustrating as advanced MD tables that you have with regular MD notes in obsidian. The dashboard tables have this awesome expanded function with a clean view and I am loving it. 

I think more people should find and use your plugin, and I'm not sure if "Dashboards" is the search they are looking for.

### Solution

I'd propose including the word "table" somewhere in your description so that that when people search "excel table. table" or anything along those lines, they can find it.

Those were the terms I was initially looking for, but then looked for "Notion tables" in which your plugin popped up since it had the "inspired by Notion.so" in the description. After digging up the plugin and looking into the documentation, I realized that dashboards was the powerful and clean looking table view that I wanted in Obsidian. One that was not dependent on pulling from notes (which is what the DB Folder uses to populate its table).

### Additional details

Love the work you're doing man. I'm going to be adding your plugin in for some views that I expect will become a part of my daily/weekly workflow. If all goes well, I definitely plan on making a video about your plugin to spread the word.

**Comment by trey-wallis** [comment]
Hi @ThisIsKeb. This is second comment I received about the name "Dashboard". See: https://github.com/trey-wallis/obsidian-dashboards/discussions/591.

I pulled the name "dashboard" from the "personal dashboards" that Tiago Forte mentions in this blog post here: https://fortelabs.com/blog/how-to-build-your-personal-productivity-stack and it's something that I've heard him call the Notion database before. A "database" is also interesting because the way Notion uses a little different than the normal term used in the software industry.

I originally had this plugin named "Notion-Like Tables" but I was recommended to change this to 1. not box myself into implementing just Notion features in this plugin and 2. remove any issues that might come with using the name Notion.

I have noticed that many of the feature requests have been related to both Notion.so and Excel Spreadsheet functionality. The main feature of the app is a table so I agree that changing the description would be good. I do envision adding a feed-like/list feature and including other sources such as tags, search terms, etc to the plugin. However, I don't tend to make the same features that Obsidian projects has. Do you have an recommendations for a better name than dashboards? I don't mind rebranding again, especially if it makes the plugin more accessible to people searching on Google or the Obsidian plugin store.

Here are a few from ChatGPT
- DataLoom: This name conveys the weaving together of diverse information sources into a cohesive whole, like threads on a loom.
- TableScape: A play on 'landscape,' this suggests a wide-ranging, versatile approach to tables.
- Obsidian Conduit: Implies that your plugin is a channel or pathway for integrating diverse data.
- InfoWeaver: This name suggests the ability to interlace different sources of information in a streamlined way.
- TableMaster: This name suggests mastery or advanced control over table functionalities.
- TableCraft: A simple, descriptive name that signals the plugin's main function of enhancing table functionalities.

@lymeswold

**Comment by lymeswold** [comment]
I like the name.
